name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker login -u tanluongdoan -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build . -t tanluongdoan/docs-astrojs:v5-2025-01-24

      - name: push image to docker hub
        run: |
          docker login -u tanluongdoan -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push tanluongdoan/docs-astrojs:v5-2025-01-24


